apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldump
data:
  Mysql_Host: ""
  Mysql_Port: ""
  Mysql_User: ""
  Mysql_Password: ""
  Mysql_AllDatabase: "true"

  QingStor_AccessorKey: ""
  QingStor_SecretKey: ""
  QingStor_Zone: ""
  QingStor_BucketName: ""
  QingStor_UploadPath: ""

  VolumeDump_Path: "/mysqldump"
