apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-import
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: mysqldump
              hostPath:
                path: /root/tmp/mysqldump
          initContainers:
            - name: download-sql
              image: 'f10atin9/download_sql:v0.1.1'
              envFrom:
                - configMapRef:
                    name: mysqldump
              volumeMounts:
                - mountPath: /mysqldump
                  name: mysqldump
              imagePullPolicy: IfNotPresent
          containers:
            - name: import-to-mysql
              image: 'f10atin9/import_sql:v0.1.1'
              envFrom:
                - configMapRef:
                    name: mysqldump
              resources: {}
              volumeMounts:
                - name: mysqldump
                  mountPath: /mysqldump
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure