apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-dump
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: mysqldump
              hostPath:
                path: /root/tmp/mysqldump
          containers:
            - name: dump-sql
              image: 'f10atin9/dump_sql:latest'
              env:
                - name: DB_HOST
                  value: ""
                - name: DB_PORT
                  value: ""
                - name: DB_USER
                  value: ""
                - name: DB_PASS
                  value: ""
                - name: ALL_DATABASES
                  value: ""
              volumeMounts:
                - mountPath: /mysqldump
                  name: mysqldump
              imagePullPolicy: IfNotPresent
            - name: upload-to-bucket
              image: 'f10atin9/upload:latest'
              args:
                - '--accessKey='
                - '--secretKey='
                - '--bucketName='
                - '--zone='
                - '--localPath='
                - '--uploadPath='
              resources: {}
              volumeMounts:
                - name: mysqldump
                  mountPath: /mysqldump
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure